
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**

        - id: complaint-service
          uri: lb://complaint-service
          predicates:
            - Path=/complaint/**

jwt:
  secret: bc534cbde41272352d1a97ae10f0af9ea0df6eeec7e3bbded9d8d5647837c361
  expiration: 30