spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**
          filters:
            - JwtAuthFilter

        - id: complaint-service
          uri: lb://complaint-service
          predicates:
            - Path=/complaint/**
          filters:
            - JwtAuthFilter